### ISSUE TITLE
Fails With Type Hints

### ISSUE THREAD

**Issue by MiConnell** [hamolicious/Auto-__init__#1]
This is a super useful extension! I noticed that it does not fill if there are type hints in the arguments.

Example:
```python
class Test:
    def __init__(self, val):
        self.val = val  # works fine
```

```python
class Test:
    def __init__(self, val: str) -> None:
        # nothing happens
```

**Comment by hamolicious** [comment]
Yes thank you for bringing this up, I was able to replicate the issue and will be working on fixing it shortly

**Comment by hamolicious** [comment]
Issue has been fixed and type hints are now supported

**Comment by MiConnell** [comment]
Thanks for the quick update, it works great!
