### ISSUE TITLE
incorrect creating self.self (for first parsed param)

### ISSUE THREAD

**Issue by otemek** [hamolicious/Auto-__init__#7]
https://github.com/hamolicious/Fillin-it/blob/67ac69286d01c310840a8d8e2959523888b18ef8/extension.js#L146

let me quickly fix it :)

**Comment by hamolicious** [comment]
Thanks a lot, haven't had a chance to look over your changes properly. Some tests might be an idea too :/.

Version v0.5.5 has just been released.
